// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: proto/enum_with_alias.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumAllowingAlias int32

const (
	EnumAllowingAlias_EAA_UNSPECIFIED EnumAllowingAlias = 0
	EnumAllowingAlias_EAA_STARTED     EnumAllowingAlias = 1
	EnumAllowingAlias_EAA_RUNNING     EnumAllowingAlias = 1
	EnumAllowingAlias_EAA_FINISHED    EnumAllowingAlias = 2
)

// Enum value maps for EnumAllowingAlias.
var (
	EnumAllowingAlias_name = map[int32]string{
		0: "EAA_UNSPECIFIED",
		1: "EAA_STARTED",
		// Duplicate value: 1: "EAA_RUNNING",
		2: "EAA_FINISHED",
	}
	EnumAllowingAlias_value = map[string]int32{
		"EAA_UNSPECIFIED": 0,
		"EAA_STARTED":     1,
		"EAA_RUNNING":     1,
		"EAA_FINISHED":    2,
	}
)

func (x EnumAllowingAlias) Enum() *EnumAllowingAlias {
	p := new(EnumAllowingAlias)
	*p = x
	return p
}

func (x EnumAllowingAlias) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumAllowingAlias) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_enum_with_alias_proto_enumTypes[0].Descriptor()
}

func (EnumAllowingAlias) Type() protoreflect.EnumType {
	return &file_proto_enum_with_alias_proto_enumTypes[0]
}

func (x EnumAllowingAlias) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumAllowingAlias.Descriptor instead.
func (EnumAllowingAlias) EnumDescriptor() ([]byte, []int) {
	return file_proto_enum_with_alias_proto_rawDescGZIP(), []int{0}
}

type EnumNotAllowingAlias int32

const (
	EnumNotAllowingAlias_ENAA_UNSPECIFIED EnumNotAllowingAlias = 0
	EnumNotAllowingAlias_ENAA_STARTED     EnumNotAllowingAlias = 1
	// ENAA_RUNNING = 1;  // Uncommenting this line will cause a warning message.
	EnumNotAllowingAlias_ENAA_FINISHED EnumNotAllowingAlias = 2
)

// Enum value maps for EnumNotAllowingAlias.
var (
	EnumNotAllowingAlias_name = map[int32]string{
		0: "ENAA_UNSPECIFIED",
		1: "ENAA_STARTED",
		2: "ENAA_FINISHED",
	}
	EnumNotAllowingAlias_value = map[string]int32{
		"ENAA_UNSPECIFIED": 0,
		"ENAA_STARTED":     1,
		"ENAA_FINISHED":    2,
	}
)

func (x EnumNotAllowingAlias) Enum() *EnumNotAllowingAlias {
	p := new(EnumNotAllowingAlias)
	*p = x
	return p
}

func (x EnumNotAllowingAlias) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumNotAllowingAlias) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_enum_with_alias_proto_enumTypes[1].Descriptor()
}

func (EnumNotAllowingAlias) Type() protoreflect.EnumType {
	return &file_proto_enum_with_alias_proto_enumTypes[1]
}

func (x EnumNotAllowingAlias) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumNotAllowingAlias.Descriptor instead.
func (EnumNotAllowingAlias) EnumDescriptor() ([]byte, []int) {
	return file_proto_enum_with_alias_proto_rawDescGZIP(), []int{1}
}

var File_proto_enum_with_alias_proto protoreflect.FileDescriptor

var file_proto_enum_with_alias_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x77, 0x69, 0x74,
	0x68, 0x5f, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2a, 0x60, 0x0a, 0x11, 0x45, 0x6e, 0x75, 0x6d, 0x41,
	0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x13, 0x0a, 0x0f,
	0x45, 0x41, 0x41, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x41, 0x41, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44,
	0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x41, 0x41, 0x5f, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e,
	0x47, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x41, 0x41, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53,
	0x48, 0x45, 0x44, 0x10, 0x02, 0x1a, 0x02, 0x10, 0x01, 0x2a, 0x51, 0x0a, 0x14, 0x45, 0x6e, 0x75,
	0x6d, 0x4e, 0x6f, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x41, 0x6c, 0x69, 0x61,
	0x73, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x41, 0x41, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x4e, 0x41, 0x41, 0x5f,
	0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x4e, 0x41,
	0x41, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x02, 0x42, 0x08, 0x5a, 0x06,
	0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_enum_with_alias_proto_rawDescOnce sync.Once
	file_proto_enum_with_alias_proto_rawDescData = file_proto_enum_with_alias_proto_rawDesc
)

func file_proto_enum_with_alias_proto_rawDescGZIP() []byte {
	file_proto_enum_with_alias_proto_rawDescOnce.Do(func() {
		file_proto_enum_with_alias_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_enum_with_alias_proto_rawDescData)
	})
	return file_proto_enum_with_alias_proto_rawDescData
}

var file_proto_enum_with_alias_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_enum_with_alias_proto_goTypes = []interface{}{
	(EnumAllowingAlias)(0),    // 0: protobuf.EnumAllowingAlias
	(EnumNotAllowingAlias)(0), // 1: protobuf.EnumNotAllowingAlias
}
var file_proto_enum_with_alias_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_enum_with_alias_proto_init() }
func file_proto_enum_with_alias_proto_init() {
	if File_proto_enum_with_alias_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_enum_with_alias_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_enum_with_alias_proto_goTypes,
		DependencyIndexes: file_proto_enum_with_alias_proto_depIdxs,
		EnumInfos:         file_proto_enum_with_alias_proto_enumTypes,
	}.Build()
	File_proto_enum_with_alias_proto = out.File
	file_proto_enum_with_alias_proto_rawDesc = nil
	file_proto_enum_with_alias_proto_goTypes = nil
	file_proto_enum_with_alias_proto_depIdxs = nil
}
